name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

  workflow_dispatch:

jobs:
  test-backend:
    name: Test backend
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - uses: docker

      - name: Test docker
        run: docker run -it hello-world

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Test docker 1
        run: docker run -it hello-world

      - name: Start keycloak
        run: docker-compose run -d --service-ports keycloak

#      - name: Sleep for 15 seconds
#        uses: nev7n/wait_for_response@v1
#        with:
#          url: 'http://localhost:8180/auth'
#          responseCode: 200
#          timeout: 30000
#          interval: 500

      - name: Run maven test
        run: mvn -B clean test